# Site settings
title: NPB

email: "sunnybenlim@gmail.com"
url: "http://sungbinlim.github.io"
github_url: "http://github.com/sungbinlim/NPB"
github_editurl: "/blob/gh-pages"
github_profile: "http://github.com/sungbinlim"
baseurl: "/NPB"
disqus_shortname: sungbinlimgithub

exclude:
  - README.md
  - _site
  
highlighter: rouge
markdown: maruku

kramdown:
  input: GFM
  syntax_highlighter: rouge
