# Site settings
title: Sungbin Lim's Blog

email: "sunnybenlim@gmail.com"
url: "http://sungbinlim.github.io"
github_url: "http://github.com/sungbinlim/sungbin"
github_editurl: "/blob/gh-pages"
github_profile: "http://github.com/sungbinlim"
baseurl: "/sungbin"
disqus_shortname: sungbinlimgithub

exclude:
  - README.md
  - _site
  
highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
